/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all indexed collections with stats
         * @description Returns every enabled collection in the registry with its current stats. Unpaginated by design: the registry is small (3 collections today) and grows only by deliberate registry changes.
         */
        get: operations["listCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one collection with stats */
        get: operations["getCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{slug}/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse a collection's NFTs
         * @description Cursor-paginated browse over a collection's NFTs with attribute filters, text search, an owner filter and sorting. Filter semantics: values of the same trait type OR together, distinct trait types AND together. Pagination is stable under live updates (cursor-based, never offset-based).
         */
        get: operations["listCollectionNfts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{slug}/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trait facets for a collection
         * @description Every trait type with its values and counts, recomputed against the active filters. Counting is disjunctive (standard marketplace behavior): counts for trait type T are computed with T's own active filter removed and every other active filter (other trait types, `q`) applied — so users can widen a selection within a type without facets collapsing to zero. Values are sorted by count descending.
         */
        get: operations["getCollectionFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full NFT detail
         * @description Full detail for one NFT: attributes, current owner, its collection, standard and burned flag.
         */
        get: operations["getNft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NFT activity timeline
         * @description Cursor-paginated on-chain event timeline for one NFT — mints, transfers, sales (with price and marketplace) and burns. Newest first.
         */
        get: operations["listNftActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/{id}/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NFT ownership history
         * @description Cursor-paginated ownership history for one NFT, newest first. The current owner is the record whose `toSlot`/`toTimestamp` are null.
         */
        get: operations["listNftOwners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{address}/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wallet portfolio across indexed collections
         * @description Every indexed NFT currently owned by a wallet, grouped by collection. Unpaginated by design: each group carries `totalCount` plus the first page of NFTs; "see all" flows page through `listCollectionNfts?owner=<address>` instead of a nested cursor.
         */
        get: operations["listWalletNfts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A collection tracked by the indexer's registry. */
        Collection: {
            /** @description URL-safe stable identifier; the public key for all collection routes. */
            slug: string;
            /** @description Display name. */
            name: string;
            /**
             * @description On-chain standard — Metaplex Token Metadata or Metaplex Core.
             * @enum {string}
             */
            standard: "token_metadata" | "core";
            /** @description On-chain collection address — the verified collection mint for `token_metadata`, the CollectionV1 asset for `core`. The two Token Metadata collection addresses are not yet recorded (team to supply); null until then. Filling them is a data change, not a contract change — never invent one. */
            address: string | null;
            /** @description Collection display image; null until media ingestion lands. */
            imageUrl: string | null;
        };
        /** @description Cached collection stats (short TTL). */
        CollectionStats: {
            /** @description Number of non-burned NFTs. */
            supply: number;
            /** @description Distinct current owners. */
            holders: number;
            /** @description On-chain events in the last 24 hours. */
            activity24h: number;
            /** @description On-chain events in the last 7 days. */
            activity7d: number;
        };
        CollectionWithStats: components["schemas"]["Collection"] & {
            stats: components["schemas"]["CollectionStats"];
        };
        NftAttribute: {
            /** @description Trait type as recorded in the source metadata (e.g. Background, Eyes, Head). */
            traitType: string;
            value: string;
        };
        /** @description The browse/list projection of an NFT. */
        NftSummary: {
            /** @description Public NFT id — the base58 mint address (`token_metadata`) or asset id (`core`). */
            id: string;
            collectionSlug: string;
            /** @description Display name from metadata. */
            name: string;
            /** @description The */
            number: number | null;
            /** @description Image URL; null when media has not been ingested. */
            imageUrl: string | null;
            burned: boolean;
        };
        NftDetail: components["schemas"]["NftSummary"] & {
            /** @enum {string} */
            standard: "token_metadata" | "core";
            /** @description Off-chain metadata URI as recorded on chain; null when unavailable. */
            metadataUri: string | null;
            /** @description Current owner (base58); null when burned. */
            owner: string | null;
            collection: components["schemas"]["Collection"];
            attributes: components["schemas"]["NftAttribute"][];
        };
        /** @description One on-chain event in an NFT's timeline. */
        ActivityEvent: {
            /** @enum {string} */
            type: "mint" | "transfer" | "sale" | "burn";
            /** @description Transaction signature (base58). */
            signature: string;
            /**
             * Format: int64
             * @description Solana slot. Serialized as a JSON number — realistic slots stay far below 2^53, so this is lossless; the server must not switch to a string encoding without a contract revision.
             */
            slot: number;
            /** Format: date-time */
            timestamp: string;
            /** @description Sending wallet; null for mints. */
            from: string | null;
            /** @description Receiving wallet; null for burns. */
            to: string | null;
            /**
             * Format: int64
             * @description Sale price in lamports; non-null only for `sale` events. JSON number — realistic prices stay far below 2^53.
             */
            priceLamports: number | null;
            /** @description Marketplace name; non-null only for `sale` events. */
            marketplace: string | null;
        };
        /** @description One ownership interval. The current owner is the record whose `toSlot`/`toTimestamp` are null. */
        OwnershipRecord: {
            /** @description Owner wallet (base58). */
            owner: string;
            /** Format: int64 */
            fromSlot: number;
            /** Format: date-time */
            fromTimestamp: string;
            /** Format: int64 */
            toSlot: number | null;
            /** Format: date-time */
            toTimestamp: string | null;
        };
        TraitFacetValue: {
            value: string;
            count: number;
        };
        TraitFacet: {
            traitType: string;
            /** @description Sorted by count descending. */
            values: components["schemas"]["TraitFacetValue"][];
        };
        PageInfo: {
            /** @description The page size that was applied. */
            limit: number;
            /** @description Opaque base64url token; pass back verbatim as `?cursor=`. Null on the last page. Clients must not parse it. */
            nextCursor: string | null;
            /** @description Total matching items; null when counting is too expensive for the query. */
            total: number | null;
        };
        WalletCollectionGroup: {
            collection: components["schemas"]["Collection"];
            /** @description Total NFTs this wallet holds in the collection. */
            totalCount: number;
            /** @description First page of the wallet's NFTs in this collection; page through `listCollectionNfts?owner=` for the rest. */
            nfts: components["schemas"]["NftSummary"][];
        };
        CollectionListResponse: {
            data: components["schemas"]["CollectionWithStats"][];
        };
        CollectionResponse: {
            data: components["schemas"]["CollectionWithStats"];
        };
        NftListResponse: {
            data: components["schemas"]["NftSummary"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        FacetsResponse: {
            data: components["schemas"]["TraitFacet"][];
        };
        NftResponse: {
            data: components["schemas"]["NftDetail"];
        };
        ActivityListResponse: {
            data: components["schemas"]["ActivityEvent"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        OwnersListResponse: {
            data: components["schemas"]["OwnershipRecord"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        WalletNftsResponse: {
            data: components["schemas"]["WalletCollectionGroup"][];
        };
        /** @description Error envelope for every non-2xx JSON response. Extends the pre-v1 `{"error": string}` shape by upgrading the value to an object; the top-level key is stable. */
        ErrorResponse: {
            error: {
                /** @description Machine-readable code. Open set — clients must tolerate unknown values. Well-known values: `bad_request`, `not_found`, `rate_limited`, `internal`. */
                code: string;
                /** @description Human-readable description; not for programmatic use. */
                message: string;
            };
        };
    };
    responses: {
        /** @description Not Modified — the client's `If-None-Match` matched the current ETag. No body. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Malformed request — unknown sort value, out-of-range limit, unparseable cursor, malformed trait filter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "RateLimit-Reset": components["headers"]["RateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Collection slug — the stable public identifier. */
        Slug: string;
        /** @description NFT id — the base58 mint address (token_metadata) or asset id (core). */
        NftId: string;
        /** @description Base58 wallet address. */
        WalletAddress: string;
        /** @description Attribute filter. Serialization is normative here, not the deepObject style (OpenAPI leaves arrays inside deepObject undefined): each selected value is one `trait[<TraitType>]=<Value>` query pair. Repeating a trait type ORs its values; distinct trait types AND together. `?trait[Background]=Pink&trait[Background]=Blue&trait[Head]=Crown` means (Background is Pink OR Blue) AND Head is Crown. Trait types and values are matched exactly (case-sensitive) against indexed attributes. */
        TraitFilter: {
            [key: string]: string[];
        };
        /** @description Free-text search over NFT name, #number and mint/asset id. */
        TextSearch: string;
        /** @description Sort order; a leading `-` means descending. `number`/`name` sort by token number and display name. `-activity` sorts by most recent on-chain activity and has no ascending form. */
        Sort: "number" | "-number" | "name" | "-name" | "-activity";
        /** @description Restrict to NFTs currently owned by this base58 wallet address. This is also the paging path for wallet portfolios (see `listWalletNfts`). */
        OwnerFilter: string;
        /** @description Opaque pagination token from `pageInfo.nextCursor`; pass it back verbatim. Clients must not parse it. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Entity tag for conditional requests; send it back via `If-None-Match` to get a 304 when the resource is unchanged. */
        ETag: string;
        /** @description Request quota in the current window (IETF draft RateLimit headers). */
        RateLimitLimit: number;
        /** @description Requests remaining in the current window. */
        RateLimitRemaining: number;
        /** @description Seconds until the current rate-limit window resets. */
        RateLimitReset: number;
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collections. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection slug — the stable public identifier. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collection. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listCollectionNfts: {
        parameters: {
            query?: {
                /** @description Attribute filter. Serialization is normative here, not the deepObject style (OpenAPI leaves arrays inside deepObject undefined): each selected value is one `trait[<TraitType>]=<Value>` query pair. Repeating a trait type ORs its values; distinct trait types AND together. `?trait[Background]=Pink&trait[Background]=Blue&trait[Head]=Crown` means (Background is Pink OR Blue) AND Head is Crown. Trait types and values are matched exactly (case-sensitive) against indexed attributes. */
                trait?: components["parameters"]["TraitFilter"];
                /** @description Free-text search over NFT name, #number and mint/asset id. */
                q?: components["parameters"]["TextSearch"];
                /** @description Sort order; a leading `-` means descending. `number`/`name` sort by token number and display name. `-activity` sorts by most recent on-chain activity and has no ascending form. */
                sort?: components["parameters"]["Sort"];
                /** @description Restrict to NFTs currently owned by this base58 wallet address. This is also the paging path for wallet portfolios (see `listWalletNfts`). */
                owner?: components["parameters"]["OwnerFilter"];
                /** @description Opaque pagination token from `pageInfo.nextCursor`; pass it back verbatim. Clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description Collection slug — the stable public identifier. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of NFTs. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NftListResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getCollectionFacets: {
        parameters: {
            query?: {
                /** @description Attribute filter. Serialization is normative here, not the deepObject style (OpenAPI leaves arrays inside deepObject undefined): each selected value is one `trait[<TraitType>]=<Value>` query pair. Repeating a trait type ORs its values; distinct trait types AND together. `?trait[Background]=Pink&trait[Background]=Blue&trait[Head]=Crown` means (Background is Pink OR Blue) AND Head is Crown. Trait types and values are matched exactly (case-sensitive) against indexed attributes. */
                trait?: components["parameters"]["TraitFilter"];
                /** @description Free-text search over NFT name, #number and mint/asset id. */
                q?: components["parameters"]["TextSearch"];
            };
            header?: never;
            path: {
                /** @description Collection slug — the stable public identifier. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The facets. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getNft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description NFT id — the base58 mint address (token_metadata) or asset id (core). */
                id: components["parameters"]["NftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The NFT. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NftResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listNftActivity: {
        parameters: {
            query?: {
                /** @description Opaque pagination token from `pageInfo.nextCursor`; pass it back verbatim. Clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description NFT id — the base58 mint address (token_metadata) or asset id (core). */
                id: components["parameters"]["NftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of events, newest first. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listNftOwners: {
        parameters: {
            query?: {
                /** @description Opaque pagination token from `pageInfo.nextCursor`; pass it back verbatim. Clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description NFT id — the base58 mint address (token_metadata) or asset id (core). */
                id: components["parameters"]["NftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of ownership records, newest first. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnersListResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listWalletNfts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Base58 wallet address. */
                address: components["parameters"]["WalletAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The portfolio, grouped by collection. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletNftsResponse"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
}
