import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // The card portraits — trait-layer stacks and logo covers — are
    // fixed-size 1:1 same-origin PNGs kept on the same plain-<img> contract
    // as ../website's piggy-art.tsx: parity between the apps, and explicit
    // control of decoding and loading. Moving the covers to next/image
    // (sharp is enabled here, unlike website) is a separate decision.
    files: ["components/piggy-art.tsx"],
    rules: { "@next/next/no-img-element": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm gen:api` from openapi/v1.yaml.
    "lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
