import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // The card portraits are a fixed-size 1:1 stack of same-origin PNGs
    // (mirroring ../website's piggy-art.tsx) — next/image has nothing to
    // optimise here; it would only add DOM and take away control of
    // decoding and loading.
    files: ["components/piggy-art.tsx"],
    rules: { "@next/next/no-img-element": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm gen:api` from openapi/v1.yaml.
    "lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
