// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Real mints and trait combinations sampled from the dressme repo's committed
// indexes; owners, signatures and Core asset ids are synthetic sentinels.
import type { components } from "@/lib/api/schema";

export const ACTIVITY = {
  "4rrfNiudjPsG8nyQxnG9z5V7dxJ3L9Xw6s3YVhg2bSLK": [
    {
      "type": "sale",
      "signature": "Sig3x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 356000000,
      "timestamp": "2026-07-31T00:00:00.000Z",
      "from": "Ho1derD111111111111111111111111111111111111",
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": 2500000000,
      "marketplace": "Magic Eden"
    },
    {
      "type": "transfer",
      "signature": "Sig2x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 350000000,
      "timestamp": "2026-07-01T00:00:00.000Z",
      "from": "Ho1derC111111111111111111111111111111111111",
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    },
    {
      "type": "mint",
      "signature": "Sig1x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "ETRUnBFRcXEYLTUfw3ysD5cvCzUBmjPwZrvbXY1rcjEf": [
    {
      "type": "mint",
      "signature": "Sig4x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "2iqkp5GhCPi7Sv75SW12PYy234R53FTe6NaEx7Uusq1k": [
    {
      "type": "mint",
      "signature": "Sig5x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "4ARZeLkMhiUEGRivcYfyCXNMUUiPqudNLXE3TfF4yXXS": [
    {
      "type": "mint",
      "signature": "Sig6x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "31dziyL4y9sZmVrHzhVDFCCSykHmDTg7vhHmj7j3xELp": [
    {
      "type": "mint",
      "signature": "Sig7x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "9EtRbErgjj8DDSdUheJnbi8zTH4TbcKunbLUrz7WWYGe": [
    {
      "type": "mint",
      "signature": "Sig8x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "G6bi8oiFGQGqg9574rsYNNnaBBXs65fBctK5JXNqoR2e": [
    {
      "type": "mint",
      "signature": "Sig9x1111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "HVHSc4Ci1EeUkxLqmzJ6ovTwYrm5jbmJV9ZXg3xewezt": [
    {
      "type": "mint",
      "signature": "Sig10x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "4TdLoQuEqBLzHRJBs6zwzeY511gMEMwSMSJeJfJYfhh5": [
    {
      "type": "mint",
      "signature": "Sig11x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "Fgvdek6PJrVDaNwhwKpQZkpUgnxTDJjCGM7TfbFU9yRJ": [
    {
      "type": "mint",
      "signature": "Sig12x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "BAGW7xL3tMn5wEva3zoTETTKUoczRNagWeb2NJPvLSz8": [
    {
      "type": "mint",
      "signature": "Sig13x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "7PDnfp5iFHt6W5F87bRNsfqMJPPXTYrhfRxhjER9hBTs": [
    {
      "type": "mint",
      "signature": "Sig14x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "D84S6r5Cdn7nijSWExrFWoXAAdNedAkw9BHhC2viHChY": [
    {
      "type": "mint",
      "signature": "Sig15x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CZKAgqu1GS4oQaKUHVt58v9tGQGAA1xxFzz6cT4xxhDx": [
    {
      "type": "mint",
      "signature": "Sig16x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "J5q8F7Uy5Ksrshhgne8Ndg2TkWyhNYLoAxE6AJUiBW1T": [
    {
      "type": "mint",
      "signature": "Sig17x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "2A5t3KU7m54XeFy32P8PtsrhvALA1BKvNnXMic8BojHX": [
    {
      "type": "mint",
      "signature": "Sig18x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "9KKe28dJY11XkV1BhFAGZQnH75weUeUdKZxcQa8ciBZ4": [
    {
      "type": "mint",
      "signature": "Sig19x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "F7HG2pmZYA2fjBNfjfrCak6S7E1B5dobDmspN7uzwSfP": [
    {
      "type": "mint",
      "signature": "Sig20x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "HHnAE4Me3L5WMWEkJdEaRwTZszbX7Ah1Y3qeGUNt7Bsf": [
    {
      "type": "mint",
      "signature": "Sig21x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "338hjnLJjx2aVBXM5ryViz41dHhFMSxHiKCRKgoyT5L5": [
    {
      "type": "mint",
      "signature": "Sig22x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "tg5SsHX6zFjsGqpu8rLZb7vJMY4rt3YUDHvQa2UqciG": [
    {
      "type": "mint",
      "signature": "Sig23x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "7w8eCjuf4ugugQwcicoQr4nCR4gVga7SL6vzTJd33kT5": [
    {
      "type": "mint",
      "signature": "Sig24x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "HxvNLUBYgLCd2yxTHdkTZ554JXnQQxgY7ozN9i9JDxnb": [
    {
      "type": "mint",
      "signature": "Sig25x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "6Unp9NUvaBv8AGUB5uMWuXAeWjfn3rwPXBxL9SrPF7vn": [
    {
      "type": "mint",
      "signature": "Sig26x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "DdasECPRgVKQFf5JhKETYEH9zAbtZMpNWuvUgTCAXU4T": [
    {
      "type": "mint",
      "signature": "Sig27x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "6MrT7xoAxiW7DGSh8BzuU6VsSKFP5uFkNrRxQuz2wE2a": [
    {
      "type": "mint",
      "signature": "Sig28x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "2VXfUgUNdEA2Tkqg9frBYNUrbAZqeoL4ycpZBsx3jCH3": [
    {
      "type": "mint",
      "signature": "Sig29x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "8b9hGZ4oxbrdjYzBHmfMatJbCqY26W5gQ2PLNULSLyKp": [
    {
      "type": "mint",
      "signature": "Sig30x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "4LKYHsSkp5QrrgVxquZsGCH1rzPrnJupnDSMeYmJZmZv": [
    {
      "type": "mint",
      "signature": "Sig31x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "7T63En9ggHLPG1gAMe5s7Y62kRcK7n4qJyFGgZ3ZxWjW": [
    {
      "type": "mint",
      "signature": "Sig32x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "qoBxQWiLSYJS6rzhyLsBvnZdwhHJH58brPCJ2yE1FBu": [
    {
      "type": "sale",
      "signature": "Sig35x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 356000000,
      "timestamp": "2026-07-31T00:00:00.000Z",
      "from": "Ho1derD111111111111111111111111111111111111",
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": 2500000000,
      "marketplace": "Magic Eden"
    },
    {
      "type": "transfer",
      "signature": "Sig34x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 350000000,
      "timestamp": "2026-07-01T00:00:00.000Z",
      "from": "Ho1derC111111111111111111111111111111111111",
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    },
    {
      "type": "mint",
      "signature": "Sig33x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "6rm6Tv5VVSr1Nv2CB9mjrbwA4pCg5koE1Rsxck4xBkQ4": [
    {
      "type": "mint",
      "signature": "Sig36x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "HVSBsX9q44hNcsFBiPCMJG9gZdkFn6bPnW3zzZDgE42J": [
    {
      "type": "mint",
      "signature": "Sig37x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "J2ATfd8avuAG8CYmz5k5TVQZKTjLUyG4yUCgTwWeP2Fv": [
    {
      "type": "mint",
      "signature": "Sig38x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "Dse1CAiNe7RKiuVfgVKE9izuEB9pZRoQoqHYBPuJpmG": [
    {
      "type": "mint",
      "signature": "Sig39x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "DDB96uaMuvCK7v3k83VL3CroUVqDMxTrs2XwWUwFLChm": [
    {
      "type": "mint",
      "signature": "Sig40x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "2yoreNi3ctjpjPCZ2xewnavQxtKffLm6QCTMAmARUtGx": [
    {
      "type": "mint",
      "signature": "Sig41x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "2EkGowwJAYYQCBYiyszamsvtEF1mujnBPn9AFEdyEZFF": [
    {
      "type": "mint",
      "signature": "Sig42x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "GD4gxAhW6L4L2LznwKjh2VsUNK75XoHcR2DFZuUoGTGv": [
    {
      "type": "mint",
      "signature": "Sig43x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "J4Sw1QhnSzKGGteADGqYnws1yKag3FvejCYVamVnrZzY": [
    {
      "type": "mint",
      "signature": "Sig44x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset1x11111111111111111111111111111111": [
    {
      "type": "sale",
      "signature": "Sig47x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 356000000,
      "timestamp": "2026-07-31T00:00:00.000Z",
      "from": "Ho1derD111111111111111111111111111111111111",
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": 2500000000,
      "marketplace": "Magic Eden"
    },
    {
      "type": "transfer",
      "signature": "Sig46x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 350000000,
      "timestamp": "2026-07-01T00:00:00.000Z",
      "from": "Ho1derC111111111111111111111111111111111111",
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    },
    {
      "type": "mint",
      "signature": "Sig45x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset2x11111111111111111111111111111111": [
    {
      "type": "mint",
      "signature": "Sig48x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "DemoWa11et111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset3x11111111111111111111111111111111": [
    {
      "type": "mint",
      "signature": "Sig49x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derC111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset4x11111111111111111111111111111111": [
    {
      "type": "mint",
      "signature": "Sig50x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derD111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset5x11111111111111111111111111111111": [
    {
      "type": "mint",
      "signature": "Sig51x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derA111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ],
  "CoreAsset6x11111111111111111111111111111111": [
    {
      "type": "mint",
      "signature": "Sig52x111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "slot": 344000000,
      "timestamp": "2026-06-01T00:00:00.000Z",
      "from": null,
      "to": "Ho1derB111111111111111111111111111111111111",
      "priceLamports": null,
      "marketplace": null
    }
  ]
} satisfies Record<string, components["schemas"]["ActivityEvent"][]>;

export const OWNERSHIP = {
  "4rrfNiudjPsG8nyQxnG9z5V7dxJ3L9Xw6s3YVhg2bSLK": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 356000000,
      "fromTimestamp": "2026-07-31T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    },
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 350000000,
      "fromTimestamp": "2026-07-01T00:00:00.000Z",
      "toSlot": 356000000,
      "toTimestamp": "2026-07-31T00:00:00.000Z"
    },
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": 350000000,
      "toTimestamp": "2026-07-01T00:00:00.000Z"
    }
  ],
  "ETRUnBFRcXEYLTUfw3ysD5cvCzUBmjPwZrvbXY1rcjEf": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "2iqkp5GhCPi7Sv75SW12PYy234R53FTe6NaEx7Uusq1k": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "4ARZeLkMhiUEGRivcYfyCXNMUUiPqudNLXE3TfF4yXXS": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "31dziyL4y9sZmVrHzhVDFCCSykHmDTg7vhHmj7j3xELp": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "9EtRbErgjj8DDSdUheJnbi8zTH4TbcKunbLUrz7WWYGe": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "G6bi8oiFGQGqg9574rsYNNnaBBXs65fBctK5JXNqoR2e": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "HVHSc4Ci1EeUkxLqmzJ6ovTwYrm5jbmJV9ZXg3xewezt": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "4TdLoQuEqBLzHRJBs6zwzeY511gMEMwSMSJeJfJYfhh5": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "Fgvdek6PJrVDaNwhwKpQZkpUgnxTDJjCGM7TfbFU9yRJ": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "BAGW7xL3tMn5wEva3zoTETTKUoczRNagWeb2NJPvLSz8": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "7PDnfp5iFHt6W5F87bRNsfqMJPPXTYrhfRxhjER9hBTs": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "D84S6r5Cdn7nijSWExrFWoXAAdNedAkw9BHhC2viHChY": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CZKAgqu1GS4oQaKUHVt58v9tGQGAA1xxFzz6cT4xxhDx": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "J5q8F7Uy5Ksrshhgne8Ndg2TkWyhNYLoAxE6AJUiBW1T": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "2A5t3KU7m54XeFy32P8PtsrhvALA1BKvNnXMic8BojHX": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "9KKe28dJY11XkV1BhFAGZQnH75weUeUdKZxcQa8ciBZ4": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "F7HG2pmZYA2fjBNfjfrCak6S7E1B5dobDmspN7uzwSfP": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "HHnAE4Me3L5WMWEkJdEaRwTZszbX7Ah1Y3qeGUNt7Bsf": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "338hjnLJjx2aVBXM5ryViz41dHhFMSxHiKCRKgoyT5L5": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "tg5SsHX6zFjsGqpu8rLZb7vJMY4rt3YUDHvQa2UqciG": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "7w8eCjuf4ugugQwcicoQr4nCR4gVga7SL6vzTJd33kT5": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "HxvNLUBYgLCd2yxTHdkTZ554JXnQQxgY7ozN9i9JDxnb": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "6Unp9NUvaBv8AGUB5uMWuXAeWjfn3rwPXBxL9SrPF7vn": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "DdasECPRgVKQFf5JhKETYEH9zAbtZMpNWuvUgTCAXU4T": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "6MrT7xoAxiW7DGSh8BzuU6VsSKFP5uFkNrRxQuz2wE2a": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "2VXfUgUNdEA2Tkqg9frBYNUrbAZqeoL4ycpZBsx3jCH3": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "8b9hGZ4oxbrdjYzBHmfMatJbCqY26W5gQ2PLNULSLyKp": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "4LKYHsSkp5QrrgVxquZsGCH1rzPrnJupnDSMeYmJZmZv": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "7T63En9ggHLPG1gAMe5s7Y62kRcK7n4qJyFGgZ3ZxWjW": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "qoBxQWiLSYJS6rzhyLsBvnZdwhHJH58brPCJ2yE1FBu": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 356000000,
      "fromTimestamp": "2026-07-31T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    },
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 350000000,
      "fromTimestamp": "2026-07-01T00:00:00.000Z",
      "toSlot": 356000000,
      "toTimestamp": "2026-07-31T00:00:00.000Z"
    },
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": 350000000,
      "toTimestamp": "2026-07-01T00:00:00.000Z"
    }
  ],
  "6rm6Tv5VVSr1Nv2CB9mjrbwA4pCg5koE1Rsxck4xBkQ4": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "HVSBsX9q44hNcsFBiPCMJG9gZdkFn6bPnW3zzZDgE42J": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "J2ATfd8avuAG8CYmz5k5TVQZKTjLUyG4yUCgTwWeP2Fv": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "Dse1CAiNe7RKiuVfgVKE9izuEB9pZRoQoqHYBPuJpmG": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "DDB96uaMuvCK7v3k83VL3CroUVqDMxTrs2XwWUwFLChm": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "2yoreNi3ctjpjPCZ2xewnavQxtKffLm6QCTMAmARUtGx": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "2EkGowwJAYYQCBYiyszamsvtEF1mujnBPn9AFEdyEZFF": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "GD4gxAhW6L4L2LznwKjh2VsUNK75XoHcR2DFZuUoGTGv": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "J4Sw1QhnSzKGGteADGqYnws1yKag3FvejCYVamVnrZzY": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CoreAsset1x11111111111111111111111111111111": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 356000000,
      "fromTimestamp": "2026-07-31T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    },
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 350000000,
      "fromTimestamp": "2026-07-01T00:00:00.000Z",
      "toSlot": 356000000,
      "toTimestamp": "2026-07-31T00:00:00.000Z"
    },
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": 350000000,
      "toTimestamp": "2026-07-01T00:00:00.000Z"
    }
  ],
  "CoreAsset2x11111111111111111111111111111111": [
    {
      "owner": "DemoWa11et111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CoreAsset3x11111111111111111111111111111111": [
    {
      "owner": "Ho1derC111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CoreAsset4x11111111111111111111111111111111": [
    {
      "owner": "Ho1derD111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CoreAsset5x11111111111111111111111111111111": [
    {
      "owner": "Ho1derA111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ],
  "CoreAsset6x11111111111111111111111111111111": [
    {
      "owner": "Ho1derB111111111111111111111111111111111111",
      "fromSlot": 344000000,
      "fromTimestamp": "2026-06-01T00:00:00.000Z",
      "toSlot": null,
      "toTimestamp": null
    }
  ]
} satisfies Record<string, components["schemas"]["OwnershipRecord"][]>;
