// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Real mints and trait combinations sampled from the dressme repo's committed
// indexes; owners, signatures, rarity ranks and Core asset ids are synthetic
// sentinels. Stats describe THIS fixture set, not the real collections.
import type { components } from "@/lib/api/schema";

export const COLLECTIONS = [
  {
    "slug": "piggy-sol-gang",
    "name": "Piggy SOL Gang",
    "standard": "token_metadata",
    "membershipRule": "tm_allowlist",
    "address": null,
    "symbol": "PSG",
    "imageUrl": null,
    "stats": {
      "supply": 119,
      "holders": 5,
      "burned": 1,
      "indexed": 120,
      "activity24h": 20,
      "activity7d": 43,
      "lastActivityAt": "2026-09-05T16:00:00.000Z",
      "holderDistribution": [
        {
          "label": "1",
          "minCount": 1,
          "maxCount": 1,
          "holders": 0,
          "assets": 0
        },
        {
          "label": "2-5",
          "minCount": 2,
          "maxCount": 5,
          "holders": 1,
          "assets": 2
        },
        {
          "label": "6+",
          "minCount": 6,
          "maxCount": null,
          "holders": 4,
          "assets": 117
        }
      ],
      "asOf": "2026-09-05T17:00:00.000Z"
    }
  },
  {
    "slug": "piggy-girl-gang",
    "name": "Piggy Girl Gang",
    "standard": "token_metadata",
    "membershipRule": "tm_allowlist",
    "address": null,
    "symbol": "PGG",
    "imageUrl": null,
    "stats": {
      "supply": 71,
      "holders": 5,
      "burned": 1,
      "indexed": 72,
      "activity24h": 13,
      "activity7d": 25,
      "lastActivityAt": "2026-09-05T15:00:00.000Z",
      "holderDistribution": [
        {
          "label": "1",
          "minCount": 1,
          "maxCount": 1,
          "holders": 0,
          "assets": 0
        },
        {
          "label": "2-5",
          "minCount": 2,
          "maxCount": 5,
          "holders": 1,
          "assets": 2
        },
        {
          "label": "6+",
          "minCount": 6,
          "maxCount": null,
          "holders": 4,
          "assets": 69
        }
      ],
      "asOf": "2026-09-05T17:00:00.000Z"
    }
  },
  {
    "slug": "piggy-gang",
    "name": "Piggy Gang",
    "standard": "core",
    "membershipRule": "core_collection",
    "address": "J3nHgSDJj6CPj2ypuDWNuvuiYii965RcSmFAPQVDWA18",
    "symbol": null,
    "imageUrl": null,
    "stats": {
      "supply": 29,
      "holders": 5,
      "burned": 1,
      "indexed": 30,
      "activity24h": 6,
      "activity7d": 13,
      "lastActivityAt": "2026-09-05T09:00:00.000Z",
      "holderDistribution": [
        {
          "label": "1",
          "minCount": 1,
          "maxCount": 1,
          "holders": 0,
          "assets": 0
        },
        {
          "label": "2-5",
          "minCount": 2,
          "maxCount": 5,
          "holders": 1,
          "assets": 2
        },
        {
          "label": "6+",
          "minCount": 6,
          "maxCount": null,
          "holders": 4,
          "assets": 27
        }
      ],
      "asOf": "2026-09-05T17:00:00.000Z"
    }
  }
] satisfies components["schemas"]["Collection"][];
