// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Real mints and trait combinations sampled from the dressme repo's committed
// indexes; owners, signatures and Core asset ids are synthetic sentinels.
import type { components } from "@/lib/api/schema";

export const COLLECTIONS = [
  {
    "slug": "piggy-sol-gang",
    "name": "Piggy SOL Gang",
    "standard": "token_metadata",
    "address": null,
    "imageUrl": null,
    "stats": {
      "supply": 10000,
      "holders": 2914,
      "activity24h": 12,
      "activity7d": 87
    }
  },
  {
    "slug": "piggy-girl-gang",
    "name": "Piggy Girl Gang",
    "standard": "token_metadata",
    "address": null,
    "imageUrl": null,
    "stats": {
      "supply": 5000,
      "holders": 1408,
      "activity24h": 5,
      "activity7d": 41
    }
  },
  {
    "slug": "piggy-gang",
    "name": "Piggy Gang",
    "standard": "core",
    "address": "J3nHgSDJj6CPj2ypuDWNuvuiYii965RcSmFAPQVDWA18",
    "imageUrl": null,
    "stats": {
      "supply": 10000,
      "holders": 3120,
      "activity24h": 18,
      "activity7d": 122
    }
  }
] satisfies components["schemas"]["CollectionWithStats"][];
