// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Real mints and trait combinations sampled from the dressme repo's committed
// indexes; owners, signatures and Core asset ids are synthetic sentinels.
import type { components } from "@/lib/api/schema";

export const DEMO_WALLET = "DemoWa11et111111111111111111111111111111111";

// The embedded collection object is joined in from COLLECTIONS at serve time
// rather than duplicated 46 times here.
export const NFTS = [
  {
    "id": "4rrfNiudjPsG8nyQxnG9z5V7dxJ3L9Xw6s3YVhg2bSLK",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #1",
    "number": 1,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Fancy Sweater"
      },
      {
        "traitType": "Eyes",
        "value": "Monocle"
      },
      {
        "traitType": "Mouth",
        "value": "Bubble Gum"
      },
      {
        "traitType": "Head",
        "value": "Afro Tail"
      },
      {
        "traitType": "Earring",
        "value": "Palette"
      }
    ]
  },
  {
    "id": "ETRUnBFRcXEYLTUfw3ysD5cvCzUBmjPwZrvbXY1rcjEf",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #2",
    "number": 2,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Eyes",
        "value": "Heart Eyes"
      },
      {
        "traitType": "Mouth",
        "value": "Biting Brush"
      },
      {
        "traitType": "Head",
        "value": "Sailor Cap"
      }
    ]
  },
  {
    "id": "2iqkp5GhCPi7Sv75SW12PYy234R53FTe6NaEx7Uusq1k",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #3",
    "number": 3,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Rich Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Crying"
      },
      {
        "traitType": "Mouth",
        "value": "Lick"
      },
      {
        "traitType": "Head",
        "value": "Fisherman Hat"
      },
      {
        "traitType": "Earring",
        "value": "Kiss"
      }
    ]
  },
  {
    "id": "4ARZeLkMhiUEGRivcYfyCXNMUUiPqudNLXE3TfF4yXXS",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #4",
    "number": 4,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Cyan"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Purple Shirt"
      },
      {
        "traitType": "Eyes",
        "value": "High"
      },
      {
        "traitType": "Mouth",
        "value": "Bubble Gum"
      },
      {
        "traitType": "Head",
        "value": "Beanie"
      },
      {
        "traitType": "Earring",
        "value": "Palette"
      }
    ]
  },
  {
    "id": "31dziyL4y9sZmVrHzhVDFCCSykHmDTg7vhHmj7j3xELp",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #5",
    "number": 5,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Yellow"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Eyes",
        "value": "Wink"
      },
      {
        "traitType": "Mouth",
        "value": "Braces"
      },
      {
        "traitType": "Head",
        "value": "Fisherman Hat"
      },
      {
        "traitType": "Earring",
        "value": "Kiss"
      }
    ]
  },
  {
    "id": "9EtRbErgjj8DDSdUheJnbi8zTH4TbcKunbLUrz7WWYGe",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #6",
    "number": 6,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Solana Tee"
      },
      {
        "traitType": "Eyes",
        "value": "Focused"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Head",
        "value": "Afro Hair"
      },
      {
        "traitType": "Earring",
        "value": "Earth"
      }
    ]
  },
  {
    "id": "G6bi8oiFGQGqg9574rsYNNnaBBXs65fBctK5JXNqoR2e",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #7",
    "number": 7,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Eyes",
        "value": "Wink"
      },
      {
        "traitType": "Mouth",
        "value": "Braces"
      },
      {
        "traitType": "Head",
        "value": "Beanie"
      },
      {
        "traitType": "Earring",
        "value": "Gold Ring"
      }
    ]
  },
  {
    "id": "HVHSc4Ci1EeUkxLqmzJ6ovTwYrm5jbmJV9ZXg3xewezt",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #8",
    "number": 8,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Eyes",
        "value": "Coin"
      },
      {
        "traitType": "Mouth",
        "value": "Beaten"
      },
      {
        "traitType": "Head",
        "value": "Red Hair"
      },
      {
        "traitType": "Earring",
        "value": "Earth"
      }
    ]
  },
  {
    "id": "4TdLoQuEqBLzHRJBs6zwzeY511gMEMwSMSJeJfJYfhh5",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #9",
    "number": 9,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Yellow"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Eyes",
        "value": "Coin"
      },
      {
        "traitType": "Mouth",
        "value": "Smiling"
      },
      {
        "traitType": "Head",
        "value": "Mohawk Hair"
      }
    ]
  },
  {
    "id": "Fgvdek6PJrVDaNwhwKpQZkpUgnxTDJjCGM7TfbFU9yRJ",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #10",
    "number": 10,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Fancy Sweater"
      },
      {
        "traitType": "Eyes",
        "value": "Closed"
      },
      {
        "traitType": "Mouth",
        "value": "Smiling"
      },
      {
        "traitType": "Earring",
        "value": "Gun"
      }
    ]
  },
  {
    "id": "BAGW7xL3tMn5wEva3zoTETTKUoczRNagWeb2NJPvLSz8",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #11",
    "number": 11,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Pocket Watch"
      },
      {
        "traitType": "Eyes",
        "value": "Coin"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Head",
        "value": "Cowboy Hat"
      }
    ]
  },
  {
    "id": "7PDnfp5iFHt6W5F87bRNsfqMJPPXTYrhfRxhjER9hBTs",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #12",
    "number": 12,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body",
        "value": "Zombie"
      },
      {
        "traitType": "Clothes",
        "value": "Red Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Coin"
      },
      {
        "traitType": "Mouth",
        "value": "Annoyed"
      },
      {
        "traitType": "Earring",
        "value": "Western"
      }
    ]
  },
  {
    "id": "D84S6r5Cdn7nijSWExrFWoXAAdNedAkw9BHhC2viHChY",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #13",
    "number": 13,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Artist Apron"
      },
      {
        "traitType": "Eyes",
        "value": "Beaten"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Head",
        "value": "Red Hair"
      },
      {
        "traitType": "Earring",
        "value": "Kiss"
      }
    ]
  },
  {
    "id": "CZKAgqu1GS4oQaKUHVt58v9tGQGAA1xxFzz6cT4xxhDx",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #14",
    "number": 14,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Bone Necklace"
      },
      {
        "traitType": "Eyes",
        "value": "High"
      },
      {
        "traitType": "Mouth",
        "value": "Weed"
      },
      {
        "traitType": "Head",
        "value": "Elf Hat"
      },
      {
        "traitType": "Earring",
        "value": "Amulet"
      }
    ]
  },
  {
    "id": "J5q8F7Uy5Ksrshhgne8Ndg2TkWyhNYLoAxE6AJUiBW1T",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #15",
    "number": 15,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Blanket"
      },
      {
        "traitType": "Eyes",
        "value": "Closed"
      },
      {
        "traitType": "Mouth",
        "value": "Weed"
      },
      {
        "traitType": "Head",
        "value": "Mushroom"
      }
    ]
  },
  {
    "id": "2A5t3KU7m54XeFy32P8PtsrhvALA1BKvNnXMic8BojHX",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #16",
    "number": 16,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Cyan"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Piggy Tee"
      },
      {
        "traitType": "Eyes",
        "value": "Open"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Head",
        "value": "Sailor Cap"
      },
      {
        "traitType": "Earring",
        "value": "Kiss"
      }
    ]
  },
  {
    "id": "9KKe28dJY11XkV1BhFAGZQnH75weUeUdKZxcQa8ciBZ4",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #17",
    "number": 17,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Artist Apron"
      },
      {
        "traitType": "Eyes",
        "value": "Open"
      },
      {
        "traitType": "Mouth",
        "value": "Cigarette"
      },
      {
        "traitType": "Head",
        "value": "Fisherman Hat"
      },
      {
        "traitType": "Earring",
        "value": "Earth"
      }
    ]
  },
  {
    "id": "F7HG2pmZYA2fjBNfjfrCak6S7E1B5dobDmspN7uzwSfP",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #18",
    "number": 18,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Piggy Tee"
      },
      {
        "traitType": "Eyes",
        "value": "Wink"
      },
      {
        "traitType": "Mouth",
        "value": "Biting Brush"
      },
      {
        "traitType": "Head",
        "value": "Sailor Cap"
      }
    ]
  },
  {
    "id": "HHnAE4Me3L5WMWEkJdEaRwTZszbX7Ah1Y3qeGUNt7Bsf",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #19",
    "number": 19,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Artist Apron"
      },
      {
        "traitType": "Eyes",
        "value": "Coin"
      },
      {
        "traitType": "Mouth",
        "value": "Weed"
      },
      {
        "traitType": "Head",
        "value": "Mushroom"
      },
      {
        "traitType": "Earring",
        "value": "Western"
      }
    ]
  },
  {
    "id": "338hjnLJjx2aVBXM5ryViz41dHhFMSxHiKCRKgoyT5L5",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #20",
    "number": 20,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Leather Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Crying"
      },
      {
        "traitType": "Mouth",
        "value": "Smiling"
      },
      {
        "traitType": "Head",
        "value": "Party Hat"
      },
      {
        "traitType": "Earring",
        "value": "Earth"
      }
    ]
  },
  {
    "id": "tg5SsHX6zFjsGqpu8rLZb7vJMY4rt3YUDHvQa2UqciG",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #21",
    "number": 21,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Purple Shirt"
      },
      {
        "traitType": "Eyes",
        "value": "Sleeping"
      },
      {
        "traitType": "Mouth",
        "value": "Party Horn"
      },
      {
        "traitType": "Head",
        "value": "Beanie"
      }
    ]
  },
  {
    "id": "7w8eCjuf4ugugQwcicoQr4nCR4gVga7SL6vzTJd33kT5",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #22",
    "number": 22,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Artist Apron"
      },
      {
        "traitType": "Eyes",
        "value": "Beaten"
      },
      {
        "traitType": "Mouth",
        "value": "Party Horn"
      },
      {
        "traitType": "Head",
        "value": "Leprechaun Hat"
      },
      {
        "traitType": "Earring",
        "value": "Weed"
      }
    ]
  },
  {
    "id": "HxvNLUBYgLCd2yxTHdkTZ554JXnQQxgY7ozN9i9JDxnb",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #23",
    "number": 23,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Leather Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "High"
      },
      {
        "traitType": "Mouth",
        "value": "Bubble Gum"
      },
      {
        "traitType": "Head",
        "value": "Fez"
      },
      {
        "traitType": "Earring",
        "value": "Kiss"
      }
    ]
  },
  {
    "id": "6Unp9NUvaBv8AGUB5uMWuXAeWjfn3rwPXBxL9SrPF7vn",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #24",
    "number": 24,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Red Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Crying"
      },
      {
        "traitType": "Mouth",
        "value": "Smiling"
      },
      {
        "traitType": "Head",
        "value": "Officer Cap"
      },
      {
        "traitType": "Earring",
        "value": "Gold Ring"
      }
    ]
  },
  {
    "id": "DdasECPRgVKQFf5JhKETYEH9zAbtZMpNWuvUgTCAXU4T",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #25",
    "number": 25,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Solana Tee"
      },
      {
        "traitType": "Eyes",
        "value": "Crying"
      },
      {
        "traitType": "Mouth",
        "value": "Bubble Gum"
      },
      {
        "traitType": "Head",
        "value": "Sailor Cap"
      },
      {
        "traitType": "Earring",
        "value": "Western"
      }
    ]
  },
  {
    "id": "6MrT7xoAxiW7DGSh8BzuU6VsSKFP5uFkNrRxQuz2wE2a",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #26",
    "number": 26,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Leather Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Laser"
      },
      {
        "traitType": "Mouth",
        "value": "Biting Brush"
      },
      {
        "traitType": "Head",
        "value": "Cowboy Hat"
      },
      {
        "traitType": "Earring",
        "value": "Western"
      }
    ]
  },
  {
    "id": "2VXfUgUNdEA2Tkqg9frBYNUrbAZqeoL4ycpZBsx3jCH3",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #27",
    "number": 27,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Blanket"
      },
      {
        "traitType": "Eyes",
        "value": "Sleeping"
      },
      {
        "traitType": "Mouth",
        "value": "Cigarette"
      },
      {
        "traitType": "Head",
        "value": "Beanie"
      },
      {
        "traitType": "Earring",
        "value": "Gold Ring"
      }
    ]
  },
  {
    "id": "8b9hGZ4oxbrdjYzBHmfMatJbCqY26W5gQ2PLNULSLyKp",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #28",
    "number": 28,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Red Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "Dollar Sign Googles"
      },
      {
        "traitType": "Mouth",
        "value": "Braces"
      },
      {
        "traitType": "Head",
        "value": "Beret"
      },
      {
        "traitType": "Earring",
        "value": "Earth"
      }
    ]
  },
  {
    "id": "4LKYHsSkp5QrrgVxquZsGCH1rzPrnJupnDSMeYmJZmZv",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #29",
    "number": 29,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Cyan"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Eyes",
        "value": "High"
      },
      {
        "traitType": "Mouth",
        "value": "Smiling"
      },
      {
        "traitType": "Head",
        "value": "Elf Hat"
      },
      {
        "traitType": "Earring",
        "value": "Gun"
      }
    ]
  },
  {
    "id": "7T63En9ggHLPG1gAMe5s7Y62kRcK7n4qJyFGgZ3ZxWjW",
    "collectionSlug": "piggy-sol-gang",
    "name": "Piggy SOL Gang #30",
    "number": 30,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Eyes",
        "value": "Focused"
      },
      {
        "traitType": "Mouth",
        "value": "Lick"
      },
      {
        "traitType": "Head",
        "value": "Officer Cap"
      },
      {
        "traitType": "Earring",
        "value": "Red Diamond"
      }
    ]
  },
  {
    "id": "qoBxQWiLSYJS6rzhyLsBvnZdwhHJH58brPCJ2yE1FBu",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #1",
    "number": 1,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Focused"
      },
      {
        "traitType": "Mouth",
        "value": "Disgusted"
      },
      {
        "traitType": "Hair",
        "value": "Yellow Hair"
      },
      {
        "traitType": "Earring",
        "value": "Solana"
      }
    ]
  },
  {
    "id": "6rm6Tv5VVSr1Nv2CB9mjrbwA4pCg5koE1Rsxck4xBkQ4",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #2",
    "number": 2,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Strawberry Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Hearth"
      },
      {
        "traitType": "Mouth",
        "value": "Lip Biting"
      },
      {
        "traitType": "Hair",
        "value": "Orange Hair"
      },
      {
        "traitType": "Hats",
        "value": "Bear Cap"
      }
    ]
  },
  {
    "id": "HVSBsX9q44hNcsFBiPCMJG9gZdkFn6bPnW3zzZDgE42J",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #3",
    "number": 3,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Teal Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Yellow Makeup"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Hair",
        "value": "Orange Hair"
      },
      {
        "traitType": "Hats",
        "value": "Orange Cap"
      },
      {
        "traitType": "Earring",
        "value": "Hearthrate"
      }
    ]
  },
  {
    "id": "J2ATfd8avuAG8CYmz5k5TVQZKTjLUyG4yUCgTwWeP2Fv",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #4",
    "number": 4,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Blue"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Dollar Sign"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Hair",
        "value": "Yellow Hair"
      },
      {
        "traitType": "Hats",
        "value": "Green Hat"
      }
    ]
  },
  {
    "id": "Dse1CAiNe7RKiuVfgVKE9izuEB9pZRoQoqHYBPuJpmG",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #5",
    "number": 5,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Cyan Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Yellow Makeup"
      },
      {
        "traitType": "Mouth",
        "value": "Toothbrush"
      },
      {
        "traitType": "Hair",
        "value": "Purple Hair"
      },
      {
        "traitType": "Hats",
        "value": "Pink Hat"
      },
      {
        "traitType": "Earring",
        "value": "Pearls"
      }
    ]
  },
  {
    "id": "DDB96uaMuvCK7v3k83VL3CroUVqDMxTrs2XwWUwFLChm",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #6",
    "number": 6,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Cyan"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Red Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Cucumber"
      },
      {
        "traitType": "Mouth",
        "value": "Toothbrush"
      },
      {
        "traitType": "Hair",
        "value": "Purple Hair"
      },
      {
        "traitType": "Hats",
        "value": "Green Beret"
      },
      {
        "traitType": "Earring",
        "value": "Daisy"
      }
    ]
  },
  {
    "id": "2yoreNi3ctjpjPCZ2xewnavQxtKffLm6QCTMAmARUtGx",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #7",
    "number": 7,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Body",
        "value": "Purple"
      },
      {
        "traitType": "Clothes",
        "value": "Blue Shirt"
      },
      {
        "traitType": "Eyes",
        "value": "Focused"
      },
      {
        "traitType": "Mouth",
        "value": "Cigarette"
      },
      {
        "traitType": "Hair",
        "value": "Purple Hair"
      },
      {
        "traitType": "Hats",
        "value": "Green Beret"
      }
    ]
  },
  {
    "id": "2EkGowwJAYYQCBYiyszamsvtEF1mujnBPn9AFEdyEZFF",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #8",
    "number": 8,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Teal Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Red Makeup"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      },
      {
        "traitType": "Hair",
        "value": "Yellow Hair"
      },
      {
        "traitType": "Hats",
        "value": "Party Hat"
      }
    ]
  },
  {
    "id": "GD4gxAhW6L4L2LznwKjh2VsUNK75XoHcR2DFZuUoGTGv",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #9",
    "number": 9,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Yellow"
      },
      {
        "traitType": "Body",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Pink Leather Jacket"
      },
      {
        "traitType": "Eyes",
        "value": "White Sunglasses"
      },
      {
        "traitType": "Mouth",
        "value": "Cigarette"
      },
      {
        "traitType": "Hair",
        "value": "Yellow Hair"
      },
      {
        "traitType": "Hats",
        "value": "Green Beret"
      },
      {
        "traitType": "Earring",
        "value": "Cherry"
      }
    ]
  },
  {
    "id": "J4Sw1QhnSzKGGteADGqYnws1yKag3FvejCYVamVnrZzY",
    "collectionSlug": "piggy-girl-gang",
    "name": "Piggy Girl Gang #10",
    "number": 10,
    "imageUrl": null,
    "burned": false,
    "standard": "token_metadata",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Purple"
      },
      {
        "traitType": "Body",
        "value": "Yellow"
      },
      {
        "traitType": "Clothes",
        "value": "Red Dress"
      },
      {
        "traitType": "Eyes",
        "value": "Close"
      },
      {
        "traitType": "Mouth",
        "value": "Disgusted"
      },
      {
        "traitType": "Hair",
        "value": "Orange Hair"
      },
      {
        "traitType": "Hats",
        "value": "Purple Hat"
      },
      {
        "traitType": "Earring",
        "value": "Smiley"
      }
    ]
  },
  {
    "id": "CoreAsset1x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#1",
    "number": 1,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Green"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Salmon"
      },
      {
        "traitType": "Clothes",
        "value": "Tux"
      },
      {
        "traitType": "Head",
        "value": "Dreads"
      },
      {
        "traitType": "Eyes",
        "value": "Terminator"
      },
      {
        "traitType": "Earring",
        "value": "Ear Tag"
      },
      {
        "traitType": "Mouth",
        "value": "Apple"
      }
    ]
  },
  {
    "id": "CoreAsset2x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#2",
    "number": 2,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "DemoWa11et111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Orange"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Dino"
      },
      {
        "traitType": "Clothes",
        "value": "Singlet"
      },
      {
        "traitType": "Head",
        "value": "Pirate Hat"
      },
      {
        "traitType": "Eyes",
        "value": "Urban Frames Glasses"
      },
      {
        "traitType": "Mouth",
        "value": "Butcher's Knife"
      }
    ]
  },
  {
    "id": "CoreAsset3x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#3",
    "number": 3,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "Ho1derC111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Earring",
        "value": "Angel Wings"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Pink"
      },
      {
        "traitType": "Clothes",
        "value": "Pimp Coat"
      },
      {
        "traitType": "Head",
        "value": "Straw Hat"
      },
      {
        "traitType": "Eyes",
        "value": "Tear Drop Tattoos"
      },
      {
        "traitType": "Mouth",
        "value": "Coin"
      }
    ]
  },
  {
    "id": "CoreAsset4x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#4",
    "number": 4,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "Ho1derD111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Cyan"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Dino"
      },
      {
        "traitType": "Clothes",
        "value": "Prison Suit"
      },
      {
        "traitType": "Head",
        "value": "Beanie"
      },
      {
        "traitType": "Eyes",
        "value": "High"
      },
      {
        "traitType": "Earring",
        "value": "Ear Tag"
      },
      {
        "traitType": "Mouth",
        "value": "Apple"
      }
    ]
  },
  {
    "id": "CoreAsset5x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#5",
    "number": 5,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "Ho1derA111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Yellow"
      },
      {
        "traitType": "Earring",
        "value": "Angel Wings"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Mud Splash"
      },
      {
        "traitType": "Head",
        "value": "Straw Hat"
      },
      {
        "traitType": "Eyes",
        "value": "Wink"
      },
      {
        "traitType": "Mouth",
        "value": "Diamond Grills"
      }
    ]
  },
  {
    "id": "CoreAsset6x11111111111111111111111111111111",
    "collectionSlug": "piggy-gang",
    "name": "#6",
    "number": 6,
    "imageUrl": null,
    "burned": false,
    "standard": "core",
    "metadataUri": null,
    "owner": "Ho1derB111111111111111111111111111111111111",
    "attributes": [
      {
        "traitType": "Background",
        "value": "Red"
      },
      {
        "traitType": "Earring",
        "value": "Wingman"
      },
      {
        "traitType": "Body | Received Mud",
        "value": "Mud Splash"
      },
      {
        "traitType": "Clothes",
        "value": "Solana Tee"
      },
      {
        "traitType": "Head",
        "value": "Hawk's Nest"
      },
      {
        "traitType": "Eyes",
        "value": "Focused"
      },
      {
        "traitType": "Mouth",
        "value": "Neutral"
      }
    ]
  }
] satisfies Omit<components["schemas"]["NftDetail"], "collection">[];
